export const PROJECTS_PAGE_CONTENT = {
  hero: {
    badge: "Warisan Kami",
    title: {
      main: "Mengubah Visi",
      highlight: "Menjadi Realita",
    },
    description: "Jelajahi beragam portofolio landmark arsitektur dan interior khusus kami, yang masing-masing menceritakan kisah unik tentang inovasi dan keahlian.",
  },
  categories: ["Semua", "Residensial", "Komersial", "Interior", "Lansekap"],
  projects: [
    {
      id: "vanguard-residence",
      title: "The Vanguard Residence",
      category: "Residensial",
      location: "Bali, Indonesia",
      year: "2023",
      area: "1.200 m²",
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "skyline-office",
      title: "Skyline Corporate Hub",
      category: "Komersial",
      location: "Jakarta, Indonesia",
      year: "2022",
      area: "5.500 m²",
      image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop",
    },
    {
      id: "minimalist-villa",
      title: "Zenith Minimalist Villa",
      category: "Residensial",
      location: "Kyoto, Jepang",
      year: "2021",
      area: "850 m²",
      image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=2000&auto=format&fit=crop",
    },
    {
      id: "urban-loft",
      title: "The Urban Loft",
      category: "Interior",
      location: "New York, AS",
      year: "2023",
      area: "250 m²",
      image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1980&auto=format&fit=crop",
    },
    {
      id: "eco-pavilion",
      title: "Eco-Garden Pavilion",
      category: "Lansekap",
      location: "Singapura",
      year: "2022",
      area: "1.500 m²",
      image: "https://images.unsplash.com/photo-1558603668-6570496b66f8?q=80&w=2000&auto=format&fit=crop",
    },
    {
      id: "heritage-hotel",
      title: "Heritage Boutique Hotel",
      category: "Komersial",
      location: "Paris, Prancis",
      year: "2021",
      area: "3.200 m²",
      image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop",
    },
  ],
};
