export const BLOG_PREVIEW_CONTENT = {
  badge: "Wawasan",
  title: "Terbaru dari Jurnal Kami",
  description: "Menjelajahi titik temu antara arsitektur modern, hunian berkelanjutan, dan desain interior inovatif.",
  articles: [
    {
      id: "blog-1",
      title: "Masa Depan Hunian Perkotaan Minimalis",
      category: "Arsitektur",
      date: "12 Mei 2024",
      readTime: "5 menit baca",
      image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=2070&auto=format&fit=crop",
      slug: "future-minimalist-urban-living",
    },
    {
      id: "blog-2",
      title: "Mengintegrasikan Ruang Hijau di Kantor Perusahaan",
      category: "Keberlanjutan",
      date: "05 Mei 2024",
      readTime: "8 menit baca",
      image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=2070&auto=format&fit=crop",
      slug: "green-spaces-corporate-offices",
    },
    {
      id: 3,
      title: "Teknik Pencahayaan untuk Interior Modern",
      category: "Interior",
      date: "28 April 2024",
      readTime: "4 menit baca",
      image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1974&auto=format&fit=crop",
      slug: "lighting-techniques-modern-interiors",
    },
  ],
  ctaLabel: "Baca Semua Jurnal",
  ctaHref: "/blog",
  pageContent: {
    badge: "Jurnal Kami",
    title: "Wawasan &",
    highlight: "Inspirasi",
    description: "Kumpulan cerita, berita, dan pembahasan mendalam tentang dunia arsitektur kontemporer dan desain interior.",
    categories: ["Semua Pos", "Arsitektur", "Interior", "Tren", "Keberlanjutan"],
  },
};
