export const BLOG_PAGE_DATA = {
  hero: {
    badge: "Our Journal",
    title: "Thought, Design &",
    highlight: "Innovation",
    description: "Deep dives into architectural philosophy, interior trends, and the stories behind our most challenging projects.",
  },
  featured: {
    id: "featured-1",
    title: "Redefining Sustainable Urbanism: The Green Spine Project",
    excerpt: "How we integrated vertical forests into high-density urban residential towers to reduce heat island effects and improve well-being.",
    category: "Architecture",
    date: "May 15, 2024",
    author: "Adrian Sterling",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop",
    readTime: "12 min read",
    slug: "redefining-sustainable-urbanism",
  },
  articles: [
    {
      id: "art-1",
      title: "The Psychology of Space: How Interiors Affect Mood",
      excerpt: "Exploring the neuro-scientific connection between spatial volume, lighting, and human emotional response.",
      category: "Interior",
      date: "May 10, 2024",
      author: "Elena Rossi",
      image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=2000&auto=format&fit=crop",
      readTime: "7 min read",
      slug: "psychology-of-space",
    },
    {
      id: "art-2",
      title: "5 Smart Home Technologies You Actually Need",
      excerpt: "Beyond the gadgets: integrating automation that enhances architectural flow and energy efficiency.",
      category: "Technology",
      date: "May 05, 2024",
      author: "Mark Jansen",
      image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=2070&auto=format&fit=crop",
      readTime: "5 min read",
      slug: "smart-home-tech-need",
    },
    {
      id: "art-3",
      title: "The Comeback of Brutalism in Modern Offices",
      excerpt: "Why concrete and raw textures are returning to corporate environments in the post-digital age.",
      category: "Trends",
      date: "April 28, 2024",
      author: "Adrian Sterling",
      image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=2011&auto=format&fit=crop",
      readTime: "9 min read",
      slug: "brutalism-modern-offices",
    },
    {
      id: "art-4",
      title: "Artisanal Craftsmanship in Bespoke Furniture",
      excerpt: "The importance of supporting local craft in an era of mass-produced interior elements.",
      category: "Design",
      date: "April 20, 2024",
      author: "Elena Rossi",
      image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1974&auto=format&fit=crop",
      readTime: "6 min read",
      slug: "artisanal-craftsmanship",
    },
    {
      id: "art-5",
      title: "Lighting Design: More Than Just Fixtures",
      excerpt: "Using light as a primary building material to define boundaries and guide circulation.",
      category: "Architecture",
      date: "April 15, 2024",
      author: "Mark Jansen",
      image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=2070&auto=format&fit=crop",
      readTime: "10 min read",
      slug: "lighting-design-material",
    },
    {
      id: "art-6",
      title: "The Evolution of Shared Workspace Post-2020",
      excerpt: "Analyzing the permanent shifts in how we design environments for collaboration and focus.",
      category: "Architecture",
      date: "April 08, 2024",
      author: "Adrian Sterling",
      image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=2069&auto=format&fit=crop",
      readTime: "15 min read",
      slug: "evolution-shared-workspace",
    },
  ],
};
