export const BLOG_PAGE_DATA = {
  hero: {
    badge: "Jurnal Kami",
    title: "Pemikiran, Desain &",
    highlight: "Inovasi",
    description: "Pembahasan mendalam tentang filosofi arsitektur, tren interior, dan cerita di balik proyek kami yang paling menantang.",
  },
  featured: {
    id: "featured-1",
    title: "Mendefinisikan Ulang Urbanisme Berkelanjutan: Proyek Green Spine",
    excerpt: "Bagaimana kami mengintegrasikan hutan vertikal ke dalam menara hunian perkotaan berkepadatan tinggi untuk mengurangi efek pulau panas dan meningkatkan kesejahteraan.",
    category: "Arsitektur",
    date: "15 Mei 2024",
    author: "Adrian Sterling",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop",
    readTime: "12 menit baca",
    slug: "redefining-sustainable-urbanism",
  },
  articles: [
    {
      id: "art-1",
      title: "Psikologi Ruang: Bagaimana Interior Mempengaruhi Suasana Hati",
      excerpt: "Menjelajahi hubungan neuro-ilmiah antara volume spasial, pencahayaan, dan respons emosional manusia.",
      category: "Interior",
      date: "10 Mei 2024",
      author: "Elena Rossi",
      image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=2000&auto=format&fit=crop",
      readTime: "7 menit baca",
      slug: "psychology-of-space",
    },
    {
      id: "art-2",
      title: "5 Teknologi Rumah Pintar yang Benar-benar Anda Butuhkan",
      excerpt: "Melampaui gadget: mengintegrasikan otomatisasi yang meningkatkan alur arsitektur dan efisiensi energi.",
      category: "Teknologi",
      date: "05 Mei 2024",
      author: "Mark Jansen",
      image: "https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=2070&auto=format&fit=crop",
      readTime: "5 menit baca",
      slug: "smart-home-tech-need",
    },
    {
      id: "art-3",
      title: "Kembalinya Brutalisme di Kantor Modern",
      excerpt: "Mengapa beton dan tekstur mentah kembali ke lingkungan perusahaan di era pasca-digital.",
      category: "Tren",
      date: "28 April 2024",
      author: "Adrian Sterling",
      image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?q=80&w=2011&auto=format&fit=crop",
      readTime: "9 menit baca",
      slug: "brutalism-modern-offices",
    },
    {
      id: "art-4",
      title: "Keahlian Pengrajin dalam Furnitur Pesanan",
      excerpt: "Pentingnya mendukung kerajinan lokal di era elemen interior produksi massal.",
      category: "Desain",
      date: "20 April 2024",
      author: "Elena Rossi",
      image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1974&auto=format&fit=crop",
      readTime: "6 menit baca",
      slug: "artisanal-craftsmanship",
    },
    {
      id: "art-5",
      title: "Desain Pencahayaan: Lebih dari Sekadar Lampu",
      excerpt: "Menggunakan cahaya sebagai bahan bangunan utama untuk menentukan batas dan memandu sirkulasi.",
      category: "Arsitektur",
      date: "15 April 2024",
      author: "Mark Jansen",
      image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=2070&auto=format&fit=crop",
      readTime: "10 menit baca",
      slug: "lighting-design-material",
    },
    {
      id: "art-6",
      title: "Evolusi Ruang Kerja Bersama Pasca-2020",
      excerpt: "Menganalisis pergeseran permanen dalam cara kita merancang lingkungan untuk kolaborasi dan fokus.",
      category: "Arsitektur",
      date: "08 April 2024",
      author: "Adrian Sterling",
      image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=2069&auto=format&fit=crop",
      readTime: "15 menit baca",
      slug: "evolution-shared-workspace",
    },
  ],
};
